export const FETCH_PLACES_REQUEST = 'FETCH_PLACES_REQUEST';
export const FETCH_PLACES_SUCCESS = 'FETCH_PLACES_SUCCESS';
export const FETCH_PLACES_FAIL = 'FETCH_PLACES_FAIL';


export const  CLEAR_ERRORS="CLEAR_ERRORS"