export const ALL_ATTRACTION_REQUEST="ALL_ATTRACTION_REQUEST";
export const ALL_ATTRACTION_SUCCESS="ALL_ATTRACTION_SUCCESS";
export const ALL_ATTRACTION_FAIL="ALL_ATTRACTION_FAIL";

export const  CLEAR_ERRORS="CLEAR_ERRORS"